### ISSUE TITLE
Add `category` and `framework` metadata fields to all rules

### ISSUE THREAD

**Issue by minusworld** [returntocorp/semgrep-rules#1307]
**Is your feature request related to a problem? Please describe.**
Instead of relying on the directory path for these, these attributes should be put in the metadata.

**Describe the solution you'd like**
Something like this:

```
metadata:
  owasp: ...
  category: security
  framework: django
```

AND probably a metalinter rule which enforces an enum on `category`, one of:
- security
- portability
- maintainability
- correctness
- best-practice
- performance

**Additional context**
This will get used in semgrep.dev's new registry search.
